"use client"
import {Inter} from "next/font/google";
import "./globals.css";
import UserAuthContext from "./contextProvider";
import {useEffect, useState} from "react";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

const inter = Inter({subsets: ["latin"]});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  const [isUserLoggedIn, setIsUserLoggedIn] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [userData, setUserData] = useState(null);
  const [refresh, setRefresh] = useState(false);
  const [categories, setCategories] = useState([]);
  const [buyingProduct, setBuyingProduct] = useState([]);
  const [paymentInfo, setPaymentInfo] = useState({});

  useEffect(() => {
    const validateUserSession = async () => {
      const sessionResponse = await fetch("/api/Authentication/ValidateSession")
      const sessionResult = await sessionResponse.json()
      if (sessionResult.status === 200) {
        setIsUserLoggedIn(true);
        fetchUserData()
      } else if (sessionResult.status === 401) {
        setIsLoading(false)
      }
    }
    validateUserSession();
  }, [isUserLoggedIn]);

  return (
    <html lang="en">
      <UserAuthContext.Provider value={{
        isUserLoggedIn,
        setIsUserLoggedIn,
      }}>
        <body className={inter.className}>
          <Navbar />
          {children}
          <Footer />
        </body>
      </UserAuthContext.Provider>
    </html>
  );
}
